services:

  samba-work:
    container_name: samba_work
    build:
      context: src
    restart: always
    cap_add:
      - NET_BIND_SERVICE
    environment:
      - UID=5537
      - GID=5537
      - USER=ware
      - PASS=***
      - SHARE=Work
      - PUBLIC=no
      - WRITABLE=yes
      - BROWSEABLE=yes
      - CREATE_MASK=0600
      - DIRECTORY_MASK=0700
    volumes:
      - /mnt/work:/data
    networks:
      macvlan_net:
        ipv4_address: 10.0.42.1

  samba-retro:
    container_name: samba_retro
    build:
      context: src
    restart: always
    cap_add:
      - NET_BIND_SERVICE
    environment:
      - UID=5538
      - GID=5538
      - WORKGROUP=RETROGROUP
      - USER=retro
      - PASS=***
      - SHARE=Retro
      - COMMENT=Retro share (insecure)
      - PUBLIC=no
      - WRITABLE=yes
      - BROWSEABLE=yes
      - CREATE_MASK=0660
      - DIRECTORY_MASK=0770
      - ALLOW_SMBV1=true
    volumes:
      - /mnt/retro:/data
    networks:
      macvlan_net:
        ipv4_address: 10.0.42.3

networks:
  macvlan_net:
    name: macvlan_net
    external: true
